// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-vIE9BVBO-eC5_faCUkIT7BZKeV9owU',
    appId: '1:274978425664:web:0745c3e43f39dd127e88a5',
    messagingSenderId: '274978425664',
    projectId: 'rev-lathnog-projects',
    authDomain: 'rev-lathnog-projects.firebaseapp.com',
    storageBucket: 'rev-lathnog-projects.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAli1WrTmyV5wteHw7Rd2HfTBci8cI5xpE',
    appId: '1:274978425664:android:ca7b6bdc740cf7dc7e88a5',
    messagingSenderId: '274978425664',
    projectId: 'rev-lathnog-projects',
    storageBucket: 'rev-lathnog-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUoF7RqiSqd3S_7i4KCeuO-MXieR0C7L8',
    appId: '1:274978425664:ios:b09a83a232b238387e88a5',
    messagingSenderId: '274978425664',
    projectId: 'rev-lathnog-projects',
    storageBucket: 'rev-lathnog-projects.appspot.com',
    iosClientId: '274978425664-vi8i5m4vfc0pal3j5pnk0e7asqnagen6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rev',
  );
}
